import { z } from "zod";

/**
 * Validation for Server Actions that take only a pending-import `id`
 * (`confirmImportAction`, `cancelImportAction`). The id is a UUID v4
 * generated by `savePendingImport`; mirroring its shape (36 hex-dash chars)
 * here rejects tampered path-style ids before they reach the filesystem.
 */
export const importIdInputSchema = z.object({
  id: z.string().regex(/^[a-f0-9-]{36}$/i, "expected 36-char UUID"),
});

export type ImportIdInput = z.infer<typeof importIdInputSchema>;

export type ImportIdValidation =
  | { success: true; data: ImportIdInput }
  | { success: false; error: z.ZodError };

export function validateImportIdInput(input: unknown): ImportIdValidation {
  return importIdInputSchema.safeParse(input);
}
